export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const POST_DELETED = 'POST_DELETED';
export const POST_DELETED_SUCCESS = 'POST_DELETED_SUCCESS';
export const POST_DELETED_ERROR = 'POST_DELETED_ERROR';

export const POST_EDITED = 'POST_EDITED';
export const START_EDITION = 'START_EDITION'
export const POST_EDITED_SUCCESS = 'POST_EDITED_SUCCESS';
export const POST_EDITED_ERROR = 'POST_EDITED_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';